redirectsOrigin = "config"
plugins = []
headers = []

[site]
name = "orcaobras"

[functions]

[functions."*"]

[build]
publish = "D:\\APPs\\OrçaObras\\Dev\\orcaobras_v001"
publishOrigin = "config"
commandOrigin = "config"
command = "echo 'No build required'"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]